# Generated by Django 4.2.5 on 2023-12-03 22:09

from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=700)),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('admin_approved', models.BooleanField(default=False)),
                ('delete_place', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, choices=[('Central Grounds', 'central'), ('North Grounds', 'north'), ('South Grounds', 'south')], max_length=15)),
                ('avg_busy_rating', models.FloatField(default=5)),
                ('avg_wifi_outlet_rating', models.FloatField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busy_rating', models.IntegerField(default=5)),
                ('wifi_outlet_rating', models.IntegerField(default=5)),
                ('description', models.CharField(max_length=500, null=True)),
                ('Place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs3240.place')),
            ],
        ),
    ]
