# Generated by Django 4.2.6 on 2023-10-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('details', models.CharField(max_length=500, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('admin_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
