# Generated by Django 4.2.6 on 2023-10-25 00:27

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cs3240', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, null=True),
        ),
    ]
