# Generated by Django 4.2.6 on 2023-11-14 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs3240', '0002_alter_place_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='avg_busy_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='place',
            name='avg_wifi_outlet_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busy_rating', models.IntegerField(default=5)),
                ('wifi_outlet_rating', models.IntegerField(default=5)),
                ('Place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs3240.place')),
            ],
        ),
    ]
