# Generated by Django 4.2.6 on 2023-11-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs3240', '0003_place_avg_busy_rating_place_avg_wifi_outlet_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
