# Generated by Django 4.2.5 on 2023-11-12 17:06

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cs3240', '0003_alter_place_address_alter_place_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200),
        ),
        migrations.AlterField(
            model_name='place',
            name='details',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
