# Generated by Django 4.2.5 on 2023-11-14 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs3240', '0006_alter_place_address_alter_place_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='location',
            field=models.CharField(blank=True, choices=[('Central Grounds', 'central'), ('North Grounds', 'north'), ('South Grounds', 'south')], max_length=15),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busy_rating', models.IntegerField(default=5)),
                ('wifi_outlet_rating', models.IntegerField(default=5)),
                ('user', models.CharField(max_length=200, null=True)),
                ('Place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs3240.place')),
            ],
        ),
    ]
