# Generated by Django 4.2.5 on 2023-11-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs3240', '0007_place_location_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
